name: supabase_extensions
description: Extensions for the Supabase client that allows faster develeopment
version: 0.6.0-alpha1
repository: https://github.com/kfiross/supabase_extensions

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sqlparser: ^0.21.0
  http: ^0.13.5
  supabase: ^1.10.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
