name: supabase_extensions
description: Extensions for the Supabase client that allows faster develeopment
version: 1.0.1
repository: https://github.com/kfiross/supabase_extensions

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqlparser: ^0.34.0
  http: ^1.1.0
  supabase: ^2.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dotenv: ^4.2.0
