name: supabase_extensions
description: extensions for Supabase
version: 0.3.1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  sqlparser: ^0.21.0
  http: ^0.13.5
  supabase: ^1.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
